sudo: required
dist: trusty
language: generic

env:
  global:
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/kuka-isir/depth_cam_extrinsics_calib/master/depth_cam_extrinsics_calib.rosinstall
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh